### PR TITLE
Convert to Swift 3.0 & Support Carthage

### PR DESCRIPTION
**Pull request by tinpont**
I'm using XCode 8.0 which make me force convert to swift 3.0.

For carthage, dynamic framework only support iOS 8.0 and above. But this will not affect cocoapods  version.

Thanks for your awesome project.

### CODE REVIEW

**Comment by MoZhouqi** [comment]
Thanks for your pull request!

**Comment by tinpont** [comment]
I will update README tomorrow.

**Comment by MoZhouqi** [comment]
I will update it and make some changes tomorrow.

**Comment by tinpont** [comment]
Okay, thanks again.

**Comment by MoZhouqi** [comment]
Done in 264cb9eb1ad996fcd7fa6ff4f4366ba8100e7f63.

**Comment by MoZhouqi** [comment]
Done in a45d0059352677fd0ac43d6ab4aec08d93a95988.

**Comment by tinpont** [comment]
I think we should import all header in KMNavigationBarTransition/KMNavigationBarTransition.h , just like AFNetworking etc.

So that people can just use @import KMNavigationBarTransistion.

**Comment by MoZhouqi** [comment]
But I should not  make the other headers to be public, they are internal in the framework.

**Comment by tinpont** [comment]
Oh, I see, sorry for my careless. I will test this commit out tomorrow. You'd better go to sleep now.   : )

**Comment by MoZhouqi** [comment]
Thank you and good night!

**Comment by tinpont** [comment]
Thanks for you work, everything works great. I create a pull request https://github.com/MoZhouqi/KMNavigationBarTransition/pull/56 to fix a little problem.

**Pull request merged**
