### PR TITLE
improve UINavigationBar appearance update & copy

### PR DESCRIPTION
**Pull request by tinpont**
This pull request makes NavigationBar appearance update & copy more completely.

### CODE REVIEW

**Comment by tinpont** [comment]
Seems that still have some problem to fix.

**Comment by tinpont** [comment]
I don't know why I just pull a little from edge will change navigation bar title color, I found out `WeChat` doesn't has this problem.

I also checkout master branch, seems have same problem. @MoZhouqi , could you please help me to review these code?

**Comment by MoZhouqi** [comment]
Hi, duplicate of https://github.com/MoZhouqi/KMNavigationBarTransition/issues/8, the library only deals with the background color of the navigation bar. If you want to change the title color, you can use the `titleView` property.

The code which you changed is through to my careful thinking and experimenting, any change is prone to bug.

**Comment by tinpont** [comment]
Could you please add a demonstrate for transition between `dark tintColor & statusBar`(light barTintColor) and `light tintColor & statusBar`(dark barTintColor)?

**Comment by MoZhouqi** [comment]
If you want yo change `tintColor`, you can set `customView` of the `UINavigationBar` / `UIBarButtonItem`.

**Comment by tinpont** [comment]
I will try this out and create a new pull request to finish demo later.

**Pull request closed without merging**
