### PR TITLE
Enable Carthage compatibility by creating a shared Framework scheme.

### PR DESCRIPTION
**Pull request by jakemarsh**

### CODE REVIEW

**Comment by MoZhouqi** [comment]
Hi, the .m files also need to be added to the framework.

**Comment by jakemarsh** [comment]
Oops! Thanks, added :+1:

**Comment by MoZhouqi** [comment]
It seems the deployment target of the framework also need to be changed.

**Comment by tinpont** [comment]
How is this going on?

**Comment by tinpont** [comment]
I make a new pull request https://github.com/MoZhouqi/KMNavigationBarTransition/pull/55 for carthage support, for who wants use this in carthage before onwer merge, add `github "tinpont/KMNavigationBarTransition"` to your `Cartfile`.

**Pull request closed without merging**
