### PR TITLE
1. 修复iOS11 scrollView bug

### PR DESCRIPTION
**Pull request by shengyangyu**
***
1. 修复iOS11 scrollView bug
***

### CODE REVIEW

**Comment by shengyangyu** [comment]
f9e18a52-d8e8-4768-bc65-fdb0eeb9ae1d

**Comment by MoZhouqi** [comment]
Hi @shengyangyu, thanks for your pull request, the code logic is duplicated, so could you use the code below and delete the comment.
```objc
UIEdgeInsets contentInset;
if (@available(iOS 11.0, *)) {
    contentInset = scrollView.adjustedContentInset;
} else {
    contentInset = scrollView.contentInset;
}
```

**Comment by MoZhouqi** [comment]
Hi @shengyangyu, thanks for your pull request, the code logic is duplicated, so the following code may be better.
```objc
        UIEdgeInsets contentInset;
#ifndef __IPHONE_11_0
        if (@available(iOS 11.0, *)) {
            contentInset = scrollView.adjustedContentInset;
        }
#else
        contentInset = scrollView.contentInset;
#endif
```

**Comment by shengyangyu** [comment]
very good for your code,thank for you!

**Pull request merged**
